{
 "title": "Dashboard-06-22-2026-15-58",
 "description": "Azure Container Apps dashboard providing individual Container App performance, scaling, and resource utilization.",
 "tags": [ "Azure-managed" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "am_ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   { "name": "ns", "label": "Namespace", "query": "Microsoft.App/containerApps" },
   {
    "name": "rg",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "res",
    "label": "Container App",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard is app-based, displaying key metrics for a container app using Azure Monitor metrics and Azure Resource Graph. \n\nIn case of issues, please ensure that:\n\n1. The [Azure Monitor data source is enabled](https://learn.microsoft.com/azure/managed-grafana/how-to-data-source-plugins-managed-identity?tabs=azure-portal).\n2. You have chosen a Container App that is not an [add-on](https://learn.microsoft.com/azure/container-apps/services). \n3. The time range is correct.\n\nRead more about monitoring your Azure Container Apps [here](https://learn.microsoft.com/azure/container-apps/observability)."
   }
  },
  {
   "title": "Current Container App Properties",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "azureResourceGraph": {
      "query": "Resources\r\n| where subscriptionId =~ '$sub'\r\n| where resourceGroup =~ '$rg'\r\n| where type =~ '$ns'\r\n| where name =~ '$res'\r\n| extend props = todynamic(properties)\r\n| extend \r\n    provisioningState = tostring(props.provisioningState),\r\n    workloadProfileName = tostring(props.workloadProfileName),\r\n    latestRevisionName = tostring(props.latestRevisionName),\r\n    activeRevisionMode = tostring(props.configuration.activeRevisionsMode),\r\n    runningStatus = tostring(props.runningStatus),\r\n    minReplicas = toint(props.template.scale.minReplicas),\r\n    maxReplicas = toint(props.template.scale.maxReplicas),\r\n    containers = props.template.containers\r\n| mv-expand container = containers\r\n| extend\r\n    workloadType = iif(isempty(workloadProfileName), \"NA - Consumption Only\", iif(workloadProfileName =~ \"Consumption\", \"Consumption\", \"Dedicated\"))\r\n| extend \r\n    image = tostring(container.image),\r\n    cpu = todouble(container.resources.cpu),\r\n    memory = todouble(trim_end(\"Gi\", tostring(container.resources.memory)))\r\n| project \r\n    ['Workload Type'] = workloadType,\r\n    ['Latest Revision Name'] = latestRevisionName,\r\n    ['Revision Mode'] = activeRevisionMode,\r\n    ['Image'] = image,\r\n    ['Min Replicas'] = minReplicas,\r\n    ['Max Replicas'] = maxReplicas,\r\n    ['Status'] = runningStatus,\r\n    ['CPU (cores)'] = cpu,\r\n    ['Memory (Gi)'] = memory"
     },
     "subscriptions": [ "$sub" ]
    }
   ]
  },
  {
   "title": "GPU Utilization Percentage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "GpuUtilizationPercentage",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Avg CPU Usage (m cores)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "UsageNanoCores",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Avg Memory Working Set Bytes (MB)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "WorkingSetBytes",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Avg CPU Usage Percentage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CpuPercentage",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Avg Memory Usage Percentage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryPercentage",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Max Total Reserved Cores",
   "type": "stat",
   "description": "For the entire Azure Container App.\n\nRevision Count x Replica Count x Reserved Cores = Total Reserved Cores",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "TotalCoresQuotaUsed",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Max Reserved Cores",
   "type": "stat",
   "description": "For container app revisions. \n\nAllocated CPU x Replica Count = Max Reserved Cores",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CoresQuotaUsed",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Max Allocated CPU (m cores)",
   "type": "stat",
   "description": "Per container",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "azureResourceGraph": {
      "query": "Resources\r\n| where subscriptionId =~ '$sub'\r\n| where resourceGroup =~ '$rg'\r\n| where type =~ '$ns'\r\n| where name =~ '$res'\r\n| extend containers = todynamic(properties.template.containers)\r\n| mv-expand containers\r\n| summarize cpu = strcat(sum(todouble(containers.resources.cpu)) * 1000, \" m cores\")"
     },
     "subscriptions": [ "$sub" ]
    }
   ]
  },
  {
   "title": "Max Allocated Memory (MB)",
   "type": "stat",
   "description": "Per container",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "azureResourceGraph": {
      "query": "Resources\r\n| where subscriptionId =~ '$sub'\r\n| where resourceGroup =~ '$rg'\r\n| where type =~ '$ns'\r\n| where name =~ '$res'\r\n| extend containers = todynamic(properties.template.containers)\r\n| mv-expand containers\r\n| summarize memory = strcat(\r\n      sum(\r\n        todouble(substring(containers.resources.memory, 0, strlen(containers.resources.memory) - 2)) \r\n        * 1000\r\n      ), \r\n    \" MB\")"
     },
     "subscriptions": [ "$sub" ]
    }
   ]
  },
  {
   "title": "Max Request Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Requests",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Max Replica Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Replicas",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Max Replica Restart Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "RestartCount",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Requests",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "PT6H"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Replica Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Replicas",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "PT6H"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Total Replica Restart Count",
   "type": "timeseries",
   "description": "Total number of restarts since the replica came online",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "RestartCount",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "PT6H"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Requests (Split by Replica/Status Code)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 }
  },
  {
   "title": "Requests by Replica",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "podName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "Requests",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Requests by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "{{statuscode}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "statusCode",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "Requests",
      "metricNamespace": "$ns",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res",
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "CPU (Split by Revision/Replica)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 }
  },
  {
   "title": "Avg CPU Usage by Revision (NanoCores)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "UsageNanoCores",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Avg CPU Usage by Replica (NanoCores)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "podName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "UsageNanoCores",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Memory (Split by Revision/Replica)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 }
  },
  {
   "title": "Avg Memory Working Set Bytes by Revision (MB)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "WorkingSetBytes",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Avg Memory Working Set Bytes by Replica (MB)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "podName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "WorkingSetBytes",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  { "title": "Replicas (Split by Revision)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Replica Count by Revision",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "revisionName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "Replicas",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Replica Restart Count by Revision",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 76 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "revisionName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "RestartCount",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  { "title": "Network Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Last Avg Network In Bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 87 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "RxBytes",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Avg Network In Bytes vs Network Out Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 87 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "TxBytes",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "RxBytes",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Last Avg Network Out Bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 91 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "TxBytes",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Network (Split by Revision/Replica)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 }
  },
  {
   "title": "Avg Network In Bytes by Revision",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "RxBytes",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Avg Network In Bytes by Replica",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 96 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "podName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "RxBytes",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Avg Network Out Bytes by Revision",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 106 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "TxBytes",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Avg Network Out Bytes by Replica",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 106 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "podName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "TxBytes",
      "metricNamespace": "$ns",
      "resources": [
       { "metricNamespace": "$ns", "resourceGroup": "$rg", "resourceName": "$res", "subscription": "$sub" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  }
 ]
}